name = "locationGenerator"
uuid = "50cc3e3c-5398-4dee-a588-36d91900d3a7"
authors = ["Alessandro Floris <floris.alessandro99@gmail.com>"]
version = "0.1.0"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
OpenStreetMapXPlot = "d3d4fdd0-c191-11e8-3358-a3629b56487d"
